version: '2'
services:
  app:
    build: .
    links:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .app.env
    volumes:
      - .:/app
  postgres:
    image: postgres:11.7
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .postgres.env
volumes:
  postgres:
